<?php

$postcodes = array(
	'Antrim'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT41%'"
	),
	'Ards'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT21%' OR LOCEMP LIKE 'BT22%' OR LOCEMP LIKE 'BT23%'"
	),
	'Armagh'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT60%' OR LOCEMP LIKE 'BT61%'"
	),
	'Ballymena'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT42%' OR LOCEMP LIKE 'BT43%' OR LOCEMP LIKE 'BT44%'"
	),
	'Ballymoney'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT53%'"
	),
	'Banbridge'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT25%' OR LOCEMP LIKE 'BT32%'"
	),
	'Belfast'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT_%' AND LOCEMP NOT LIKE 'BT41%' AND LOCEMP NOT LIKE 'BT21%' AND LOCEMP NOT LIKE 'BT22%' AND LOCEMP NOT LIKE 'BT23%' AND LOCEMP NOT LIKE 'BT60%' AND LOCEMP NOT LIKE 'BT61%' AND LOCEMP NOT LIKE 'BT42%' AND LOCEMP NOT LIKE 'BT43%' AND LOCEMP NOT LIKE 'BT44%' AND LOCEMP NOT LIKE 'BT53%' AND LOCEMP NOT LIKE 'BT25%' AND LOCEMP NOT LIKE 'BT32%' AND LOCEMP NOT LIKE 'BT38%' AND LOCEMP NOT LIKE 'BT51%' AND LOCEMP NOT LIKE 'BT52%' AND LOCEMP NOT LIKE 'BT80%' AND LOCEMP NOT LIKE 'BT62%' AND LOCEMP NOT LIKE 'BT63%' AND LOCEMP NOT LIKE 'BT64%' AND LOCEMP NOT LIKE 'BT65%' AND LOCEMP NOT LIKE 'BT66%' AND LOCEMP NOT LIKE 'BT67%' AND LOCEMP NOT LIKE 'BT47%' AND LOCEMP NOT LIKE 'BT48%' AND LOCEMP NOT LIKE 'BT24%' AND LOCEMP NOT LIKE 'BT30%' AND LOCEMP NOT LIKE 'BT31%' AND LOCEMP NOT LIKE 'BT33%' AND LOCEMP NOT LIKE 'BT68%' AND LOCEMP NOT LIKE 'BT69%' AND LOCEMP NOT LIKE 'BT70%' AND LOCEMP NOT LIKE 'BT71%' AND LOCEMP NOT LIKE 'BT76%' AND LOCEMP NOT LIKE 'BT77%' AND LOCEMP NOT LIKE 'BT74%' AND LOCEMP NOT LIKE 'BT75%' AND LOCEMP NOT LIKE 'BT92%' AND LOCEMP NOT LIKE 'BT93%' AND LOCEMP NOT LIKE 'BT94%' AND LOCEMP NOT LIKE 'BT49%' AND LOCEMP NOT LIKE 'BT26%' AND LOCEMP NOT LIKE 'BT27%' AND LOCEMP NOT LIKE 'BT28%' AND LOCEMP NOT LIKE 'BT45%' AND LOCEMP NOT LIKE 'BT46%' AND LOCEMP NOT LIKE 'BT54%' AND LOCEMP NOT LIKE 'BT34%' AND LOCEMP NOT LIKE 'BT35%' AND LOCEMP NOT LIKE 'BT36%' AND LOCEMP NOT LIKE 'BT37%' AND LOCEMP NOT LIKE 'BT39%' AND LOCEMP NOT LIKE 'BT18%' AND LOCEMP NOT LIKE 'BT19%' AND LOCEMP NOT LIKE 'BT20%' AND LOCEMP NOT LIKE 'BT78%' AND LOCEMP NOT LIKE 'BT79%' AND LOCEMP NOT LIKE 'BT81%' AND LOCEMP NOT LIKE 'BT82%' AND LOCEMP NOT LIKE 'BT40%'"
	),
	'Carrickfergus'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT38%'"
	),
	'Castlereagh'	=> array(
		'sql'	=> "1 = 0" # no postcode specified for this one for some reason so added false statement
	),
	'Coleraine'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT51%' OR LOCEMP LIKE 'BT52%'"
	),
	'Cookstown'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT80%'"
	),
	'Craigavon'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT62%' OR LOCEMP LIKE 'BT63%' OR LOCEMP LIKE 'BT64%' OR LOCEMP LIKE 'BT65%' OR LOCEMP LIKE 'BT66%' OR LOCEMP LIKE 'BT67%'"
	),
	'Derry'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT47%' OR LOCEMP LIKE 'BT48%'"
	),
	'Down'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT24%' OR LOCEMP LIKE 'BT30%' OR LOCEMP LIKE 'BT31%' OR LOCEMP LIKE 'BT33%'"
	),
	'Dungannon and South Tyrone'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT68%' OR LOCEMP LIKE 'BT69%' OR LOCEMP LIKE 'BT70%' OR LOCEMP LIKE 'BT71%' OR LOCEMP LIKE 'BT76%' OR LOCEMP LIKE 'BT77%'"
	),
	'Fermanagh'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT74%' OR LOCEMP LIKE 'BT75%' OR LOCEMP LIKE 'BT92%' OR LOCEMP LIKE 'BT93%' OR LOCEMP LIKE 'BT94%'"
	),
	'Larne'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT40%'"
	),
	'Limavady'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT49%'"
	),
	'Lisburn'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT26%' OR LOCEMP LIKE 'BT27%' OR LOCEMP LIKE 'BT28%'"
	),
	'Magherafelt'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT45%' OR LOCEMP LIKE 'BT46%'"
	),
	'Moyle'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT54%'"
	),
	'Newry and Mourne'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT34%' OR LOCEMP LIKE 'BT35%'"
	),
	'Newtownabbey'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT36%' OR LOCEMP LIKE 'BT37%' OR LOCEMP LIKE 'BT39%'"
	),
	'North Down'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT18%' OR LOCEMP LIKE 'BT19%' OR LOCEMP LIKE 'BT20%'"
	),
	'Omagh'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT78%' OR LOCEMP LIKE 'BT79%'"
	),
	'Strabane'	=> array(
		'sql'	=> "LOCEMP LIKE 'BT81%' OR LOCEMP LIKE 'BT82%'"
	),
	'Aberdeen City'	=> array(
		'sql'	=> "LOCEMP LIKE 'AB1%' OR LOCEMP LIKE 'AB2%' OR LOCEMP LIKE 'ZE_%'"
	),
	'Aberdeenshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'AB_%' AND LOCEMP NOT LIKE 'AB1%' AND LOCEMP NOT LIKE 'AB2%' AND LOCEMP NOT LIKE 'AB37%' AND LOCEMP NOT LIKE 'AB38%' AND LOCEMP NOT LIKE 'AB55%' AND LOCEMP NOT LIKE 'AB56%'"
	),
	'Angus'	=> array(
		'sql'	=> "LOCEMP LIKE 'DD8%' OR LOCEMP LIKE 'DD9%' OR LOCEMP LIKE 'DD10%' OR LOCEMP LIKE 'DD11%'"
	),
	'Argyll and Bute'	=> array(
		'sql'	=> "LOCEMP LIKE 'G84%' OR LOCEMP LIKE 'PA20%' OR LOCEMP LIKE 'PA21%' OR LOCEMP LIKE 'PA22%' OR LOCEMP LIKE 'PA23%' OR LOCEMP LIKE 'PA24%' OR LOCEMP LIKE 'PA25%' OR LOCEMP LIKE 'PA26%' OR LOCEMP LIKE 'PA27%' OR LOCEMP LIKE 'PA28%' OR LOCEMP LIKE 'PA29%' OR LOCEMP LIKE 'PA30%' OR LOCEMP LIKE 'PA31%' OR LOCEMP LIKE 'PA32%' OR LOCEMP LIKE 'PA33%' OR LOCEMP LIKE 'PA34%' OR LOCEMP LIKE 'PA35%' OR LOCEMP LIKE 'PA36%' OR LOCEMP LIKE 'PA37%' OR LOCEMP LIKE 'PA38%' OR LOCEMP LIKE 'PA41%' OR LOCEMP LIKE 'PA42%' OR LOCEMP LIKE 'PA43%' OR LOCEMP LIKE 'PA44%' OR LOCEMP LIKE 'PA45%' OR LOCEMP LIKE 'PA46%' OR LOCEMP LIKE 'PA47%' OR LOCEMP LIKE 'PA48%' OR LOCEMP LIKE 'PA49%' OR LOCEMP LIKE 'PA60%' OR LOCEMP LIKE 'PA61%' OR LOCEMP LIKE 'PA62%' OR LOCEMP LIKE 'PA63%' OR LOCEMP LIKE 'PA64%' OR LOCEMP LIKE 'PA65%' OR LOCEMP LIKE 'PA66%' OR LOCEMP LIKE 'PA67%' OR LOCEMP LIKE 'PA68%' OR LOCEMP LIKE 'PA69%' OR LOCEMP LIKE 'PA70%' OR LOCEMP LIKE 'PA71%' OR LOCEMP LIKE 'PA72%' OR LOCEMP LIKE 'PA73%' OR LOCEMP LIKE 'PA74%' OR LOCEMP LIKE 'PA75%' OR LOCEMP LIKE 'PA76%' OR LOCEMP LIKE 'PA77%' OR LOCEMP LIKE 'PA78%'"
	),
	'Clackmannanshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'FK10%' OR LOCEMP LIKE 'FK11%' OR LOCEMP LIKE 'FK12%' OR LOCEMP LIKE 'FK13%' OR LOCEMP LIKE 'FK14%'"
	),
	'Dumfries and Galloway'	=> array(
		'sql'	=> "LOCEMP LIKE 'DG_%'"
	),
	'Dundee City'	=> array(
		'sql'	=> "LOCEMP LIKE 'DD_%' AND LOCEMP NOT LIKE 'DD6%' AND LOCEMP NOT LIKE 'DD7%' AND LOCEMP NOT LIKE 'DD8%' AND LOCEMP NOT LIKE 'DD9%' AND LOCEMP NOT LIKE 'DD10%' AND LOCEMP NOT LIKE 'DD11%'"
	),
	'East Ayrshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'KA_%'"
	),
	'East Dunbartonshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'G61%' OR LOCEMP LIKE 'G62%' OR LOCEMP LIKE 'G64%' OR LOCEMP LIKE 'G66%'"
	),
	'East Lothian'	=> array(
		'sql'	=> "LOCEMP LIKE 'EH21%' OR LOCEMP LIKE 'EH31%' OR LOCEMP LIKE 'EH32%' OR LOCEMP LIKE 'EH33%' OR LOCEMP LIKE 'EH34%' OR LOCEMP LIKE 'EH35%' OR LOCEMP LIKE 'EH36%' OR LOCEMP LIKE 'EH39%' OR LOCEMP LIKE 'EH40%' OR LOCEMP LIKE 'EH41%' OR LOCEMP LIKE 'EH42%'"
	),
	'East Renfrewshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'G46%' OR LOCEMP LIKE 'G76%' OR LOCEMP LIKE 'G77%' OR LOCEMP LIKE 'G78%'"
	),
	'City of Edinburgh'	=> array(
		'sql'	=> "LOCEMP LIKE 'EH_%' AND LOCEMP NOT LIKE 'EH21%' AND LOCEMP NOT LIKE 'EH31%' AND LOCEMP NOT LIKE 'EH32%' AND LOCEMP NOT LIKE 'EH33%' AND LOCEMP NOT LIKE 'EH34%' AND LOCEMP NOT LIKE 'EH35%' AND LOCEMP NOT LIKE 'EH36%' AND LOCEMP NOT LIKE 'EH39%' AND LOCEMP NOT LIKE 'EH40%' AND LOCEMP NOT LIKE 'EH41%' AND LOCEMP NOT LIKE 'EH42%' AND LOCEMP NOT LIKE 'EH18%' AND LOCEMP NOT LIKE 'EH19%' AND LOCEMP NOT LIKE 'EH20%' AND LOCEMP NOT LIKE 'EH22%' AND LOCEMP NOT LIKE 'EH23%' AND LOCEMP NOT LIKE 'EH24%' AND LOCEMP NOT LIKE 'EH25%' AND LOCEMP NOT LIKE 'EH26%' AND LOCEMP NOT LIKE 'EH37%' AND LOCEMP NOT LIKE 'EH38%' AND LOCEMP NOT LIKE 'EH43%' AND LOCEMP NOT LIKE 'EH44%' AND LOCEMP NOT LIKE 'EH45%' AND LOCEMP NOT LIKE 'EH46%' AND LOCEMP NOT LIKE 'EH27%' AND LOCEMP NOT LIKE 'EH47%' AND LOCEMP NOT LIKE 'EH48%' AND LOCEMP NOT LIKE 'EH49%' AND LOCEMP NOT LIKE 'EH52%' AND LOCEMP NOT LIKE 'EH53%' AND LOCEMP NOT LIKE 'EH54%' AND LOCEMP NOT LIKE 'EH55%'"
	),
	'Falkirk'	=> array(
		'sql'	=> "LOCEMP LIKE 'EH51%' OR (LOCEMP LIKE 'FK_%' AND LOCEMP LIKE 'FK10%' AND LOCEMP NOT LIKE 'FK11%' AND LOCEMP NOT LIKE 'FK12%' AND LOCEMP NOT LIKE 'FK13%' AND LOCEMP NOT LIKE 'FK14%' AND LOCEMP NOT LIKE 'FK7%' AND LOCEMP NOT LIKE 'FK8%' AND LOCEMP NOT LIKE 'FK9%' AND LOCEMP NOT LIKE 'FK15%' AND LOCEMP NOT LIKE 'FK16%' AND LOCEMP NOT LIKE 'FK17%' AND LOCEMP NOT LIKE 'FK18%' AND LOCEMP NOT LIKE 'FK19%' AND LOCEMP NOT LIKE 'FK20%' AND LOCEMP NOT LIKE 'FK21%')"
	),
	'Fife'	=> array(
		'sql'	=> "LOCEMP LIKE 'DD6%' OR LOCEMP LIKE 'DD7%'"
	),
	'Glasgow City'	=> array(
		'sql'	=> "LOCEMP REGEXP '^G[0-9]+' AND LOCEMP NOT LIKE 'G61%' AND LOCEMP NOT LIKE 'G62%' AND LOCEMP NOT LIKE 'G64%' AND LOCEMP NOT LIKE 'G66%' AND LOCEMP NOT LIKE 'G46%' AND LOCEMP NOT LIKE 'G76%' AND LOCEMP NOT LIKE 'G77%' AND LOCEMP NOT LIKE 'G78%' AND LOCEMP NOT LIKE 'G65%' AND LOCEMP NOT LIKE 'G67%' AND LOCEMP NOT LIKE 'G68%' AND LOCEMP NOT LIKE 'G70%' AND LOCEMP NOT LIKE 'G60%' AND LOCEMP NOT LIKE 'G81%' AND LOCEMP NOT LIKE 'G82%' AND LOCEMP NOT LIKE 'G83%' AND LOCEMP NOT LIKE 'G63%' AND LOCEMP NOT LIKE 'G65%' AND LOCEMP NOT LIKE 'G67%' AND LOCEMP NOT LIKE 'G68%' AND LOCEMP NOT LIKE 'G70%' AND LOCEMP NOT LIKE 'G71%' AND LOCEMP NOT LIKE 'G72%' AND LOCEMP NOT LIKE 'G73%' AND LOCEMP NOT LIKE 'G74%' AND LOCEMP NOT LIKE 'G75%' AND LOCEMP NOT LIKE 'G79%'"
	),
	'Highland'	=> array(
		'sql'	=> "LOCEMP LIKE 'IV_%' AND LOCEMP NOT LIKE 'IV30%' AND LOCEMP NOT LIKE 'IV31%' AND LOCEMP NOT LIKE 'IV32%' AND LOCEMP NOT LIKE 'IV36%' OR (LOCEMP LIKE 'KW_%' AND LOCEMP NOT LIKE 'KW15%' AND LOCEMP NOT LIKE 'KW16%' AND LOCEMP NOT LIKE 'KW17%') OR LOCEMP LIKE 'PA80%' OR LOCEMP LIKE 'PH19%' OR LOCEMP LIKE 'PH20%' OR LOCEMP LIKE 'PH21%' OR LOCEMP LIKE 'PH22%' OR LOCEMP LIKE 'PH23%' OR LOCEMP LIKE 'PH24%' OR LOCEMP LIKE 'PH25%' OR LOCEMP LIKE 'PH26%' OR LOCEMP LIKE 'PH30%' OR LOCEMP LIKE 'PH31%' OR LOCEMP LIKE 'PH32%' OR LOCEMP LIKE 'PH33%' OR LOCEMP LIKE 'PH34%' OR LOCEMP LIKE 'PH35%' OR LOCEMP LIKE 'PH36%' OR LOCEMP LIKE 'PH37%' OR LOCEMP LIKE 'PH38%' OR LOCEMP LIKE 'PH39%' OR LOCEMP LIKE 'PH40%' OR LOCEMP LIKE 'PH41%' OR LOCEMP LIKE 'PH42%' OR LOCEMP LIKE 'PH43%' OR LOCEMP LIKE 'PH44%' OR LOCEMP LIKE 'PH50%'"
	),
	'Inverclyde'	=> array(
		'sql'	=> "LOCEMP LIKE 'PA13%' OR LOCEMP LIKE 'PA14%' OR LOCEMP LIKE 'PA15%' OR LOCEMP LIKE 'PA16%' OR LOCEMP LIKE 'PA18%' OR LOCEMP LIKE 'PA19%'"
	),
	'Midlothian'	=> array(
		'sql'	=> "LOCEMP LIKE 'EH18%' OR LOCEMP LIKE 'EH19%' OR LOCEMP LIKE 'EH20%' OR LOCEMP LIKE 'EH22%' OR LOCEMP LIKE 'EH23%' OR LOCEMP LIKE 'EH24%' OR LOCEMP LIKE 'EH25%' OR LOCEMP LIKE 'EH26%' OR LOCEMP LIKE 'EH37%' OR LOCEMP LIKE 'EH38%'"
	),
	'Moray'	=> array(
		'sql'	=> "LOCEMP LIKE 'AB37%' OR LOCEMP LIKE 'AB38%' OR LOCEMP LIKE 'AB55%' OR LOCEMP LIKE 'AB56%' OR LOCEMP LIKE 'IV30%' OR LOCEMP LIKE 'IV31%' OR LOCEMP LIKE 'IV32%' OR LOCEMP LIKE 'IV36%'"
	),
	'Na h-Eilanan Siar'	=> array(
		'sql'	=> "LOCEMP LIKE 'HS_%' OR (LOCEMP LIKE 'KY_%' AND LOCEMP NOT LIKE 'KY13%')"
	),
	'North Ayrshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'PA17%'"
	),
	'North Lanarkshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'G65%' OR LOCEMP LIKE 'G67%' OR LOCEMP LIKE 'G68%' OR LOCEMP LIKE 'G70%'"
	),
	'Orkney Islands'	=> array(
		'sql'	=> "LOCEMP LIKE 'KW15%' OR LOCEMP LIKE 'KW16%' OR LOCEMP LIKE 'KW17%'"
	),
	'Perth and Kinross'	=> array(
		'sql'	=> "LOCEMP LIKE 'KY13%' OR (LOCEMP LIKE 'PH_%' AND LOCEMP NOT LIKE 'PH19%' AND LOCEMP NOT LIKE 'PH20%' AND LOCEMP NOT LIKE 'PH21%' AND LOCEMP NOT LIKE 'PH22%' AND LOCEMP NOT LIKE 'PH23%' AND LOCEMP NOT LIKE 'PH24%' AND LOCEMP NOT LIKE 'PH25%' AND LOCEMP NOT LIKE 'PH26%' AND LOCEMP NOT LIKE 'PH30%' AND LOCEMP NOT LIKE 'PH31%' AND LOCEMP NOT LIKE 'PH32%' AND LOCEMP NOT LIKE 'PH33%' AND LOCEMP NOT LIKE 'PH34%' AND LOCEMP NOT LIKE 'PH35%' AND LOCEMP NOT LIKE 'PH36%' AND LOCEMP NOT LIKE 'PH37%' AND LOCEMP NOT LIKE 'PH38%' AND LOCEMP NOT LIKE 'PH39%' AND LOCEMP NOT LIKE 'PH40%' AND LOCEMP NOT LIKE 'PH41%' AND LOCEMP NOT LIKE 'PH42%' AND LOCEMP NOT LIKE 'PH43%' AND LOCEMP NOT LIKE 'PH44%' AND LOCEMP NOT LIKE 'PH50%')"
	),
	'Renfrewshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'ML1%' OR LOCEMP LIKE 'ML2%' OR LOCEMP LIKE 'ML4%' OR LOCEMP LIKE 'ML6%' OR LOCEMP LIKE 'ML7%' OR LOCEMP LIKE 'ML5%' OR (LOCEMP LIKE 'PA_%' AND LOCEMP NOT LIKE 'PA20%' AND LOCEMP NOT LIKE 'PA21%' AND LOCEMP NOT LIKE 'PA22%' AND LOCEMP NOT LIKE 'PA23%' AND LOCEMP NOT LIKE 'PA24%' AND LOCEMP NOT LIKE 'PA25%' AND LOCEMP NOT LIKE 'PA26%' AND LOCEMP NOT LIKE 'PA27%' AND LOCEMP NOT LIKE 'PA28%' AND LOCEMP NOT LIKE 'PA29%' AND LOCEMP NOT LIKE 'PA30%' AND LOCEMP NOT LIKE 'PA31%' AND LOCEMP NOT LIKE 'PA32%' AND LOCEMP NOT LIKE 'PA33%' AND LOCEMP NOT LIKE 'PA34%' AND LOCEMP NOT LIKE 'PA35%' AND LOCEMP NOT LIKE 'PA36%' AND LOCEMP NOT LIKE 'PA37%' AND LOCEMP NOT LIKE 'PA38%' AND LOCEMP NOT LIKE 'PA41%' AND LOCEMP NOT LIKE 'PA42%' AND LOCEMP NOT LIKE 'PA43%' AND LOCEMP NOT LIKE 'PA44%' AND LOCEMP NOT LIKE 'PA45%' AND LOCEMP NOT LIKE 'PA46%' AND LOCEMP NOT LIKE 'PA47%' AND LOCEMP NOT LIKE 'PA48%' AND LOCEMP NOT LIKE 'PA49%' AND LOCEMP NOT LIKE 'PA60%' AND LOCEMP NOT LIKE 'PA61%' AND LOCEMP NOT LIKE 'PA62%' AND LOCEMP NOT LIKE 'PA63%' AND LOCEMP NOT LIKE 'PA64%' AND LOCEMP NOT LIKE 'PA65%' AND LOCEMP NOT LIKE 'PA66%' AND LOCEMP NOT LIKE 'PA67%' AND LOCEMP NOT LIKE 'PA68%' AND LOCEMP NOT LIKE 'PA69%' AND LOCEMP NOT LIKE 'PA70%' AND LOCEMP NOT LIKE 'PA71%' AND LOCEMP NOT LIKE 'PA72%' AND LOCEMP NOT LIKE 'PA73%' AND LOCEMP NOT LIKE 'PA74%' AND LOCEMP NOT LIKE 'PA75%' AND LOCEMP NOT LIKE 'PA76%' AND LOCEMP NOT LIKE 'PA77%' AND LOCEMP NOT LIKE 'PA78%' AND LOCEMP NOT LIKE 'PA13%' AND LOCEMP NOT LIKE 'PA14%' AND LOCEMP NOT LIKE 'PA15%' AND LOCEMP NOT LIKE 'PA16%' AND LOCEMP NOT LIKE 'PA18%' AND LOCEMP NOT LIKE 'PA19%' AND LOCEMP NOT LIKE 'PA17%' AND LOCEMP NOT LIKE 'PA80%')"
	),
	'Scottish Borders'	=> array(
		'sql'	=> "LOCEMP LIKE 'EH43%' OR LOCEMP LIKE 'EH44%' OR LOCEMP LIKE 'EH45%' OR LOCEMP LIKE 'EH46%' OR (LOCEMP LIKE 'TD_%' AND LOCEMP NOT LIKE 'TD15%')"
	),
	'Shetland Islands'	=> array(
		'sql'	=> "1 = 0" # no postcode data in the old GEMS code for this so leaving false value in
	),
	'South Ayrshire'	=> array(
		'sql'	=> "1 = 0" # no postcode data in the old GEMS code for this so leaving false value in
	),
	'South Lanarkshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'G71%' OR LOCEMP LIKE 'G72%' OR LOCEMP LIKE 'G73%' OR LOCEMP LIKE 'G74%' OR LOCEMP LIKE 'G75%' OR LOCEMP LIKE 'G79%' OR (LOCEMP LIKE 'ML_%' AND LOCEMP NOT LIKE 'ML1%' AND LOCEMP NOT LIKE 'ML2%' AND LOCEMP NOT LIKE 'ML4%' AND LOCEMP NOT LIKE 'ML6%' AND LOCEMP NOT LIKE 'ML7%' AND LOCEMP LIKE 'ML5%')"
	),
	'Stirling'	=> array(
		'sql'	=> "LOCEMP LIKE 'G63%' OR LOCEMP LIKE 'FK7%' OR LOCEMP LIKE 'FK8%' OR LOCEMP LIKE 'FK9%' OR LOCEMP LIKE 'FK15%' OR LOCEMP LIKE 'FK16%' OR LOCEMP LIKE 'FK17%' OR LOCEMP LIKE 'FK18%' OR LOCEMP LIKE 'FK19%' OR LOCEMP LIKE 'FK20%' OR LOCEMP LIKE 'FK21%'"
	),
	'West Dunbartonshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'G60%' OR LOCEMP LIKE 'G81%' OR LOCEMP LIKE 'G82%' OR LOCEMP LIKE 'G83%'"
	),
	'West Lothian'	=> array(
		'sql'	=> "LOCEMP LIKE 'EH27%' OR LOCEMP LIKE 'EH47%' OR LOCEMP LIKE 'EH48%' OR LOCEMP LIKE 'EH49%' OR LOCEMP LIKE 'EH52%' OR LOCEMP LIKE 'EH53%' OR LOCEMP LIKE 'EH54%' OR LOCEMP LIKE 'EH55%'"
	),
	'Blaenau Gwent'	=> array(
		'sql'	=> "LOCEMP LIKE 'NP13%' OR LOCEMP LIKE 'NP22%' OR LOCEMP LIKE 'NP23%' OR LOCEMP LIKE 'NP24%'"
	),
	'Bridgend'	=> array(
		'sql'	=> "LOCEMP LIKE 'CF31%' OR LOCEMP LIKE 'CF32%' OR LOCEMP LIKE 'CF33%' OR LOCEMP LIKE 'CF34%' OR LOCEMP LIKE 'CF35%' OR LOCEMP LIKE 'CF36%'"
	),
	'Caerphilly'	=> array(
		'sql'	=> "LOCEMP LIKE 'NP11%' OR LOCEMP LIKE 'NP12%' OR LOCEMP LIKE 'CF81%' OR LOCEMP LIKE 'CF82%' OR LOCEMP LIKE 'CF83%'"
	),
	'Cardiff'	=> array(
		'sql'	=> "LOCEMP LIKE 'CF_%' AND LOCEMP NOT LIKE 'CF31%' AND LOCEMP NOT LIKE 'CF32%' AND LOCEMP NOT LIKE 'CF33%' AND LOCEMP NOT LIKE 'CF34%' AND LOCEMP NOT LIKE 'CF35%' AND LOCEMP NOT LIKE 'CF36%' AND LOCEMP NOT LIKE 'CF37%' AND LOCEMP NOT LIKE 'CF38%' AND LOCEMP NOT LIKE 'CF39%' AND LOCEMP NOT LIKE 'CF40%' AND LOCEMP NOT LIKE 'CF41%' AND LOCEMP NOT LIKE 'CF42%' AND LOCEMP NOT LIKE 'CF43%' AND LOCEMP NOT LIKE 'CF44%' AND LOCEMP NOT LIKE 'CF45%' AND LOCEMP NOT LIKE 'CF72%' AND LOCEMP NOT LIKE 'CF46%' AND LOCEMP NOT LIKE 'CF81%' AND LOCEMP NOT LIKE 'CF82%' AND LOCEMP NOT LIKE 'CF83%'"
	),
	'Carmarthenshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'SA14%' OR LOCEMP LIKE 'SA15%' OR LOCEMP LIKE 'SA16%' OR LOCEMP LIKE 'SA17%' OR LOCEMP LIKE 'SA18%' OR LOCEMP LIKE 'SA19%' OR LOCEMP LIKE 'SA20%' OR LOCEMP LIKE 'SA31%' OR LOCEMP LIKE 'SA32%' OR LOCEMP LIKE 'SA33%' OR LOCEMP LIKE 'SA34%' OR LOCEMP LIKE 'SA38%' OR LOCEMP LIKE 'SA39%' OR LOCEMP LIKE 'SA40%' OR LOCEMP LIKE 'SA41%'"
	),
	'Ceredigion'	=> array(
		'sql'	=> "LOCEMP LIKE 'SA43%' OR LOCEMP LIKE 'SA44%' OR LOCEMP LIKE 'SA45%' OR LOCEMP LIKE 'SA46%' OR LOCEMP LIKE 'SA47%' OR LOCEMP LIKE 'SA48%' OR LOCEMP LIKE 'SY23%' OR LOCEMP LIKE 'SY24%' OR LOCEMP LIKE 'SY25%'"
	),
	'Conwy'	=> array(
		'sql'	=> "LOCEMP LIKE 'LL22%' OR LOCEMP LIKE 'LL24%' OR LOCEMP LIKE 'LL25%' OR LOCEMP LIKE 'LL26%' OR LOCEMP LIKE 'LL27%' OR LOCEMP LIKE 'LL28%' OR LOCEMP LIKE 'LL29%' OR LOCEMP LIKE 'LL30%' OR LOCEMP LIKE 'LL31%' OR LOCEMP LIKE 'LL32%' OR LOCEMP LIKE 'LL33%' OR LOCEMP LIKE 'LL34%'"
	),
	'Denbighshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'LL15%' OR LOCEMP LIKE 'LL16%' OR LOCEMP LIKE 'LL17%' OR LOCEMP LIKE 'LL18%' OR LOCEMP LIKE 'LL19%' OR LOCEMP LIKE 'LL20%' OR LOCEMP LIKE 'LL21%'"
	),
	'Flintshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'CH5%' OR LOCEMP LIKE 'CH6%' OR LOCEMP LIKE 'CH7%' OR LOCEMP LIKE 'CH8%'"
	),
	'Gwynedd'	=> array(
		'sql'	=> "LOCEMP LIKE 'LL23%' OR LOCEMP LIKE 'LL3%' OR LOCEMP LIKE 'LL4%' OR LOCEMP LIKE 'LL5%'"
	),
	'Isle of Anglesey'	=> array(
		'sql'	=> "LOCEMP LIKE 'LL58%' OR LOCEMP LIKE 'LL59%' OR LOCEMP LIKE 'LL6%' OR LOCEMP LIKE 'LL7%'"
	),
	'Merthyr Tydfil'	=> array(
		'sql'	=> "LOCEMP LIKE 'CF46%'"
	),
	'Monmouthshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'LNP_%' AND LOCEMP NOT LIKE 'NP13%' AND LOCEMP NOT LIKE 'NP22%' AND LOCEMP NOT LIKE 'NP23%' AND LOCEMP NOT LIKE 'NP24%' AND LOCEMP NOT LIKE 'NP11%' AND LOCEMP NOT LIKE 'NP12%' AND LOCEMP NOT LIKE 'NP8%' AND LOCEMP NOT LIKE 'NP4%'"
	),
	'Neath Port Talbot'	=> array(
		'sql'	=> "LOCEMP LIKE 'SA8%' OR LOCEMP LIKE 'SA9%' OR LOCEMP LIKE 'SA10%' OR LOCEMP LIKE 'SA11%' OR LOCEMP LIKE 'SA12%' OR LOCEMP LIKE 'SA13%'"
	),
	'Newport'	=> array(
		'sql'	=> "LOCEMP LIKE 'NP10%' OR LOCEMP LIKE 'NP18%' OR LOCEMP LIKE 'NP19%' OR LOCEMP LIKE 'NP20%'"
	),
	'Pembrokeshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'SA35%' OR LOCEMP LIKE 'SA36%' OR LOCEMP LIKE 'SA37%' OR LOCEMP LIKE 'SA61%' OR LOCEMP LIKE 'SA62%' OR LOCEMP LIKE 'SA63%' OR LOCEMP LIKE 'SA64%' OR LOCEMP LIKE 'SA65%' OR LOCEMP LIKE 'SA66%' OR LOCEMP LIKE 'SA67%' OR LOCEMP LIKE 'SA68%' OR LOCEMP LIKE 'SA69%' OR LOCEMP LIKE 'SA70%' OR LOCEMP LIKE 'SA71%' OR LOCEMP LIKE 'SA72%' OR LOCEMP LIKE 'SA73%'"
	),
	'Powys'	=> array(
		'sql'	=> "LOCEMP LIKE 'LD_%' OR LOCEMP LIKE 'NP8%' OR LOCEMP LIKE 'SY15%' OR LOCEMP LIKE 'SY16%' OR LOCEMP LIKE 'SY17%' OR LOCEMP LIKE 'SY18%' OR LOCEMP LIKE 'SY19%' OR LOCEMP LIKE 'SY20%' OR LOCEMP LIKE 'SY21%' OR LOCEMP LIKE 'SY22%'"
	),
	'Rhondda'	=> array(
		'sql'	=> "LOCEMP LIKE 'CF37%' OR LOCEMP LIKE 'CF38%' OR LOCEMP LIKE 'CF39%' OR LOCEMP LIKE 'CF40%' OR LOCEMP LIKE 'CF41%' OR LOCEMP LIKE 'CF42%' OR LOCEMP LIKE 'CF43%' OR LOCEMP LIKE 'CF44%' OR LOCEMP LIKE 'CF45%' OR LOCEMP LIKE 'CF72%'"
	),
	'Swansea'	=> array(
		'sql'	=> "LOCEMP LIKE 'SA_%' AND LOCEMP NOT LIKE 'SA35%' AND LOCEMP NOT LIKE 'SA36%' AND LOCEMP NOT LIKE 'SA37%' AND LOCEMP NOT LIKE 'SA61%' AND LOCEMP NOT LIKE 'SA62%' AND LOCEMP NOT LIKE 'SA63%' AND LOCEMP NOT LIKE 'SA64%' AND LOCEMP NOT LIKE 'SA65%' AND LOCEMP NOT LIKE 'SA66%' AND LOCEMP NOT LIKE 'SA67%' AND LOCEMP NOT LIKE 'SA68%' AND LOCEMP NOT LIKE 'SA69%' AND LOCEMP NOT LIKE 'SA70%' AND LOCEMP NOT LIKE 'SA71%' AND LOCEMP NOT LIKE 'SA72%' AND LOCEMP NOT LIKE 'SA73%' AND LOCEMP NOT LIKE 'SA8%' AND LOCEMP NOT LIKE 'SA9%' AND LOCEMP NOT LIKE 'SA10%' AND LOCEMP NOT LIKE 'SA11%' AND LOCEMP NOT LIKE 'SA12%' AND LOCEMP NOT LIKE 'SA13%' AND LOCEMP NOT LIKE 'SA14%' AND LOCEMP NOT LIKE 'SA15%' AND LOCEMP NOT LIKE 'SA16%' AND LOCEMP NOT LIKE 'SA17%' AND LOCEMP NOT LIKE 'SA18%' AND LOCEMP NOT LIKE 'SA19%' AND LOCEMP NOT LIKE 'SA20%' AND LOCEMP NOT LIKE 'SA31%' AND LOCEMP NOT LIKE 'SA32%' AND LOCEMP NOT LIKE 'SA33%' AND LOCEMP NOT LIKE 'SA34%' AND LOCEMP NOT LIKE 'SA38%' AND LOCEMP NOT LIKE 'SA39%' AND LOCEMP NOT LIKE 'SA40%' AND LOCEMP NOT LIKE 'SA41%' AND LOCEMP NOT LIKE 'SA43%' AND LOCEMP NOT LIKE 'SA44%' AND LOCEMP NOT LIKE 'SA45%' AND LOCEMP NOT LIKE 'SA46%' AND LOCEMP NOT LIKE 'SA47%' AND LOCEMP NOT LIKE 'SA48%'"
	),
	'Torfaen'	=> array(
		'sql'	=> "LOCEMP LIKE 'NP4%'"
	),
	'Vale of Glamorgan'	=> array(
		'sql'	=> "LOCEMP LIKE 'CF61%' OR LOCEMP LIKE 'CF62%' OR LOCEMP LIKE 'CF63%' OR LOCEMP LIKE 'CF64%' OR LOCEMP LIKE 'CF71%'"
	),
	'Wrexham'	=> array(
		'sql'	=> "LOCEMP LIKE 'LL11%' OR LOCEMP LIKE 'LL12%' OR LOCEMP LIKE 'LL13%' OR LOCEMP LIKE 'LL14%'"
	),
	'Derbyshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'NG10%' OR LOCEMP LIKE 'NG20%' OR LOCEMP LIKE 'NG31%' OR LOCEMP LIKE 'NG32%' OR LOCEMP LIKE 'NG33%' OR LOCEMP LIKE 'NG34%' OR LOCEMP LIKE 'SK13%' OR LOCEMP LIKE 'SK17%' OR LOCEMP LIKE 'SK22%' OR LOCEMP LIKE 'SK23%' OR LOCEMP LIKE 'S18%' OR LOCEMP LIKE 'S21%' OR LOCEMP LIKE 'S32%' OR LOCEMP LIKE 'S33%' OR LOCEMP LIKE 'S40%' OR LOCEMP LIKE 'S41%' OR LOCEMP LIKE 'S42%' OR LOCEMP LIKE 'S43%' OR LOCEMP LIKE 'S44%' OR LOCEMP LIKE 'S45%' OR LOCEMP LIKE 'S49%' OR (LOCEMP LIKE 'DE_%' AND LOCEMP NOT LIKE 'DE12%' AND LOCEMP NOT LIKE 'DE74%' AND LOCEMP NOT LIKE 'DE14%' AND LOCEMP NOT LIKE 'DE15%')"
	),
	'Leicestershire'	=> array(
		'sql'	=> "LOCEMP LIKE 'LE_%' AND LOCEMP NOT LIKE 'LE15%' OR LOCEMP LIKE 'CV13%' OR LOCEMP LIKE 'DE12%' OR LOCEMP LIKE 'DE74%'"
	),
	'Lincolnshire (E. Midlands part)'	=> array(
		'sql'	=> "LOCEMP LIKE 'LN_%' OR LOCEMP LIKE 'DN21%' OR LOCEMP LIKE 'DN36%' OR LOCEMP LIKE 'PE6%' OR LOCEMP LIKE 'PE9%' OR LOCEMP LIKE 'PE10%' OR LOCEMP LIKE 'PE11%' OR LOCEMP LIKE 'PE12%' OR LOCEMP LIKE 'PE20%' OR LOCEMP LIKE 'PE21%' OR LOCEMP LIKE 'PE22%' OR LOCEMP LIKE 'PE23%' OR LOCEMP LIKE 'PE24%' OR LOCEMP LIKE 'PE25%'"
	),
	'Northamptonshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'OX17%' OR LOCEMP LIKE 'PE8%'"
	),
	'Nottinghamshire'	=> array(
		'sql'	=> "(LOCEMP LIKE 'NG_%' AND LOCEMP NOT LIKE 'NG10%' AND LOCEMP NOT LIKE 'NG20%' AND LOCEMP NOT LIKE 'NG31%' AND LOCEMP NOT LIKE 'NG32%' AND LOCEMP NOT LIKE 'NG33%' AND LOCEMP NOT LIKE 'NG34%') OR LOCEMP LIKE 'NN_%' OR LOCEMP LIKE 'S80%' OR LOCEMP LIKE 'S81%' OR LOCEMP LIKE 'DN10%' OR LOCEMP LIKE 'DN11%' OR LOCEMP LIKE 'DN22%'"
	),
	'Rutland'	=> array(
		'sql'	=> "LOCEMP LIKE 'LE15%'"
	),
	'Bedfordshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'LU_%' OR LOCEMP LIKE 'MK40%' OR LOCEMP LIKE 'MK41%' OR LOCEMP LIKE 'MK42%' OR LOCEMP LIKE 'MK43%' OR LOCEMP LIKE 'MK44%' OR LOCEMP LIKE 'MK45%' OR LOCEMP LIKE 'SG15%' OR LOCEMP LIKE 'SG16%' OR LOCEMP LIKE 'SG17%' OR LOCEMP LIKE 'SG18%' OR LOCEMP LIKE 'SG19%'"
	),
	'Cambridgeshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'CB_%' AND LOCEMP NOT LIKE 'CB8%' AND LOCEMP NOT LIKE 'CB9%' AND LOCEMP NOT LIKE 'CB10%' AND LOCEMP NOT LIKE 'CB11%' OR (LOCEMP LIKE 'PE_%' AND LOCEMP NOT LIKE 'PE6%' AND LOCEMP NOT LIKE 'PE9%' AND LOCEMP NOT LIKE 'PE10%' AND LOCEMP NOT LIKE 'PE11%' AND LOCEMP NOT LIKE 'PE12%' AND LOCEMP NOT LIKE 'PE20%' AND LOCEMP NOT LIKE 'PE21%' AND LOCEMP NOT LIKE 'PE22%' AND LOCEMP NOT LIKE 'PE23%' AND LOCEMP NOT LIKE 'PE24%' AND LOCEMP NOT LIKE 'PE25%' AND LOCEMP NOT LIKE 'PE30%' AND LOCEMP NOT LIKE 'PE31%' AND LOCEMP NOT LIKE 'PE32%' AND LOCEMP NOT LIKE 'PE33%' AND LOCEMP NOT LIKE 'PE34%' AND LOCEMP NOT LIKE 'PE35%' AND LOCEMP NOT LIKE 'PE36%' AND LOCEMP NOT LIKE 'PE37%' AND LOCEMP NOT LIKE 'PE38%' AND LOCEMP NOT LIKE 'PE8%')"
	),
	'Essex'	=> array(
		'sql'	=> "LOCEMP LIKE 'EN9%' OR LOCEMP LIKE 'SS_%' OR LOCEMP LIKE 'CB10%' OR LOCEMP LIKE 'CB11%' OR (LOCEMP LIKE 'CM_%' AND LOCEMP NOT LIKE 'CM21%' AND LOCEMP NOT LIKE 'CM22%' AND LOCEMP NOT LIKE 'CM23%') OR LOCEMP LIKE 'CO_%' OR LOCEMP LIKE 'IG7%' OR LOCEMP LIKE 'IG9%' OR LOCEMP LIKE 'IG10%' OR LOCEMP LIKE 'RM15%' OR LOCEMP LIKE 'RM16%' OR LOCEMP LIKE 'RM17%' OR LOCEMP LIKE 'RM18%' OR LOCEMP LIKE 'RM19%' OR LOCEMP LIKE 'RM20%'"
	),
	'Hertfordshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'EN11%' OR LOCEMP LIKE 'EN10%' OR LOCEMP LIKE 'EN8%' OR LOCEMP LIKE 'EN7%' OR LOCEMP LIKE 'EN6%' OR (LOCEMP LIKE 'SG_%' AND LOCEMP NOT LIKE 'SG15%' AND LOCEMP NOT LIKE 'SG16%' AND LOCEMP NOT LIKE 'SG17%' AND LOCEMP NOT LIKE 'SG18%' AND LOCEMP NOT LIKE 'SG19%') OR LOCEMP LIKE 'WD_%' OR LOCEMP LIKE 'AL_%' OR LOCEMP LIKE 'CM21%' OR LOCEMP LIKE 'CM22%' OR LOCEMP LIKE 'CM23%' OR (LOCEMP LIKE 'HP_%' AND LOCEMP NOT LIKE 'HP5%' AND LOCEMP NOT LIKE 'HP6%' AND LOCEMP NOT LIKE 'HP7%' AND LOCEMP NOT LIKE 'HP8%' AND LOCEMP NOT LIKE 'HP9%' AND LOCEMP NOT LIKE 'HP10%' AND LOCEMP NOT LIKE 'HP11%' AND LOCEMP NOT LIKE 'HP12%' AND LOCEMP NOT LIKE 'HP13%' AND LOCEMP NOT LIKE 'HP14%' AND LOCEMP NOT LIKE 'HP15%' AND LOCEMP NOT LIKE 'HP16%' AND LOCEMP NOT LIKE 'HP17%' AND LOCEMP NOT LIKE 'HP18%' AND LOCEMP NOT LIKE 'HP19%' AND LOCEMP NOT LIKE 'HP20%' AND LOCEMP NOT LIKE 'HP21%' AND LOCEMP NOT LIKE 'HP22%' AND LOCEMP NOT LIKE 'HP27%')"
	),
	'Norfolk'	=> array(
		'sql'	=> "(LOCEMP LIKE 'NR_%' AND LOCEMP NOT LIKE 'NR32%' AND LOCEMP NOT LIKE 'NR33%' AND LOCEMP NOT LIKE 'NR34%' AND LOCEMP NOT LIKE 'NR35%') OR LOCEMP LIKE 'IP22%' OR LOCEMP LIKE 'IP24%' OR LOCEMP LIKE 'IP25%' OR LOCEMP LIKE 'IP26%' OR LOCEMP LIKE 'PE30%' OR LOCEMP LIKE 'PE31%' OR LOCEMP LIKE 'PE32%' OR LOCEMP LIKE 'PE33%' OR LOCEMP LIKE 'PE34%' OR LOCEMP LIKE 'PE35%' OR LOCEMP LIKE 'PE36%' OR LOCEMP LIKE 'PE37%' OR LOCEMP LIKE 'PE38%'"
	),
	'Suffolk'	=> array(
		'sql'	=> "LOCEMP LIKE 'NR32%' OR LOCEMP LIKE 'NR33%' OR LOCEMP LIKE 'NR34%' OR LOCEMP LIKE 'NR35%' OR LOCEMP LIKE 'CB8%' OR LOCEMP LIKE 'CB9%' OR (LOCEMP LIKE 'IP_%' AND LOCEMP NOT LIKE 'IP22%' AND LOCEMP NOT LIKE 'IP24%' AND LOCEMP NOT LIKE 'IP25%' AND LOCEMP NOT LIKE 'IP26%')"
	),
	'North London'	=> array(
		'sql'	=> "(LOCEMP LIKE 'EC1%' AND LOCEMP NOT LIKE 'EC1P%' AND LOCEMP NOT LIKE 'EC2P%' AND LOCEMP NOT LIKE 'EC3P%' AND LOCEMP NOT LIKE 'EC4P%' AND LOCEMP NOT LIKE 'EC50%' AND LOCEMP NOT LIKE 'EC1A%' ) OR LOCEMP LIKE 'EC2A%' OR (LOCEMP LIKE 'EN%' AND LOCEMP NOT LIKE 'EN9%' AND LOCEMP NOT LIKE 'EN11%' AND LOCEMP NOT LIKE 'EN10%' AND LOCEMP NOT LIKE 'EN8%' AND LOCEMP NOT LIKE 'EN7%' AND LOCEMP NOT LIKE 'EN6%') OR LOCEMP LIKE 'E5%' OR LOCEMP LIKE 'E8%' OR LOCEMP LIKE 'E9%' OR LOCEMP LIKE 'E10%' OR (LOCEMP LIKE 'NW_%' AND LOCEMP NOT LIKE 'NW6%' AND LOCEMP NOT LIKE 'NW10%') OR LOCEMP REGEXP '^N[0-9]+' OR LOCEMP LIKE 'SW1A%' OR LOCEMP LIKE 'SW1E%' OR LOCEMP LIKE 'SW1H%' OR LOCEMP LIKE 'SW1P%' OR LOCEMP LIKE 'SW1V%' OR LOCEMP LIKE 'SW1W%' OR LOCEMP LIKE 'SW1X%' OR LOCEMP LIKE 'SW1Y%' OR LOCEMP LIKE 'WC_%' OR (LOCEMP REGEXP '^W[0-9]+' AND LOCEMP NOT LIKE 'W3%' AND LOCEMP NOT LIKE 'W4%' AND LOCEMP NOT LIKE 'W5%' AND LOCEMP NOT LIKE 'W6%' AND LOCEMP NOT LIKE 'W7%' AND LOCEMP NOT LIKE 'W8%' AND LOCEMP NOT LIKE 'W10%' AND LOCEMP NOT LIKE 'W11%' AND LOCEMP NOT LIKE 'W12%' AND LOCEMP NOT LIKE 'W13%' AND LOCEMP NOT LIKE 'W14%') OR LOCEMP LIKE 'HA8%'"
	),
	'North East London'	=> array(
		'sql'	=> "LOCEMP LIKE 'EC1P%' OR LOCEMP LIKE 'EC2P%' OR LOCEMP LIKE 'EC3P%' OR LOCEMP LIKE 'EC4P%' OR LOCEMP LIKE 'EC50%' OR LOCEMP LIKE 'EC1A%' OR (LOCEMP REGEXP '^E[0-9]+' AND LOCEMP NOT LIKE 'E5%' AND LOCEMP NOT LIKE 'E8%' AND LOCEMP NOT LIKE 'E9%' AND LOCEMP NOT LIKE 'E10%') OR (LOCEMP LIKE 'IG_%' AND LOCEMP NOT LIKE 'IG7%' AND LOCEMP NOT LIKE 'IG9%' AND LOCEMP NOT LIKE 'IG10%') OR (LOCEMP LIKE 'RM_%' AND LOCEMP NOT LIKE 'RM15%' AND LOCEMP NOT LIKE 'RM16%' AND LOCEMP NOT LIKE 'RM17%' AND LOCEMP NOT LIKE 'RM18%' AND LOCEMP NOT LIKE 'RM19%' AND LOCEMP NOT LIKE 'RM20%') OR (LOCEMP LIKE 'EC%' AND LOCEMP NOT LIKE 'EC1%' AND LOCEMP NOT LIKE 'EC2A%')"
	),
	'South East London'	=> array(
		'sql'	=> "LOCEMP LIKE 'BR_%' AND LOCEMP NOT LIKE 'BR8%' OR (LOCEMP LIKE 'SE_%' AND LOCEMP NOT LIKE 'SE11%' AND LOCEMP NOT LIKE 'SE19%' AND LOCEMP NOT LIKE 'SE24%' AND LOCEMP NOT LIKE 'SE25%' AND LOCEMP NOT LIKE 'SE27%') OR LOCEMP LIKE 'TN14%' OR LOCEMP LIKE 'TN16%'"
	),
	'South West London'	=> array(
		'sql'	=> "LOCEMP LIKE 'SE11%' OR LOCEMP LIKE 'SE19%' OR LOCEMP LIKE 'SE24%' OR LOCEMP LIKE 'SE25%' OR LOCEMP LIKE 'SE27%' OR (LOCEMP LIKE 'SM_%' and LOCEMP NOT LIKE 'SM7%') OR LOCEMP LIKE 'SW2%' OR LOCEMP LIKE 'SW4%' OR LOCEMP LIKE 'SW8%' OR LOCEMP LIKE 'SW9%' OR (LOCEMP LIKE 'CR_%' AND LOCEMP NOT LIKE 'CR6%') OR LOCEMP LIKE 'DA6%' OR LOCEMP LIKE 'DA7%' OR LOCEMP LIKE 'DA8%' OR LOCEMP LIKE 'DA14%' OR LOCEMP LIKE 'DA15%' OR LOCEMP LIKE 'DA16%' OR LOCEMP LIKE 'DA17%' OR LOCEMP LIKE 'DA18%' OR LOCEMP LIKE 'DA5%' OR (LOCEMP LIKE 'KT_%' AND LOCEMP NOT LIKE 'KT7%' AND LOCEMP NOT LIKE 'KT8%' AND LOCEMP NOT LIKE 'KT10%' AND LOCEMP NOT LIKE 'KT11%' AND LOCEMP NOT LIKE 'KT12%' AND LOCEMP NOT LIKE 'KT13%' AND LOCEMP NOT LIKE 'KT14%' AND LOCEMP NOT LIKE 'KT15%' AND LOCEMP NOT LIKE 'KT16%' AND LOCEMP NOT LIKE 'KT17%' AND LOCEMP NOT LIKE 'KT18%' AND LOCEMP NOT LIKE 'KT19%' AND LOCEMP NOT LIKE 'KT20%' AND LOCEMP NOT LIKE 'KT21%' AND LOCEMP NOT LIKE 'KT22%' AND LOCEMP NOT LIKE 'KT23%' AND LOCEMP NOT LIKE 'KT24%') OR (LOCEMP LIKE 'TW_%' AND LOCEMP NOT LIKE 'TW15%' AND LOCEMP NOT LIKE 'TW16%' AND LOCEMP NOT LIKE 'TW17%' AND LOCEMP NOT LIKE 'TW18%' AND LOCEMP NOT LIKE 'TW19%' AND LOCEMP NOT LIKE 'TW20%' AND LOCEMP NOT LIKE 'TW3%' AND LOCEMP NOT LIKE 'TW4%' AND LOCEMP NOT LIKE 'TW5%' AND LOCEMP NOT LIKE 'TW6%' AND LOCEMP NOT LIKE 'TW7%' AND LOCEMP NOT LIKE 'TW8%' AND LOCEMP NOT LIKE 'TW13%' AND LOCEMP NOT LIKE 'TW14%')"
	),
	'West London'	=> array(
		'sql'	=> "LOCEMP LIKE 'NW6%' OR LOCEMP LIKE 'NW10%' OR (LOCEMP LIKE 'SW_%' AND LOCEMP NOT LIKE 'SW2%' AND LOCEMP NOT LIKE 'SW4%' AND LOCEMP NOT LIKE 'SW8%' AND LOCEMP NOT LIKE 'SW9%' AND LOCEMP NOT LIKE 'SW1A%' AND LOCEMP NOT LIKE 'SW1E%' AND LOCEMP NOT LIKE 'SW1H%' AND LOCEMP NOT LIKE 'SW1P%' AND LOCEMP NOT LIKE 'SW1V%' AND LOCEMP NOT LIKE 'SW1W%' AND LOCEMP NOT LIKE 'SW1X%' AND LOCEMP NOT LIKE 'SW1Y%') OR LOCEMP LIKE 'W3%' OR LOCEMP LIKE 'W4%' OR LOCEMP LIKE 'W5%' OR LOCEMP LIKE 'W6%' OR LOCEMP LIKE 'W7%' OR LOCEMP LIKE 'W8%' OR LOCEMP LIKE 'W10%' OR LOCEMP LIKE 'W11%' OR LOCEMP LIKE 'W12%' OR LOCEMP LIKE 'W13%' OR LOCEMP LIKE 'W14%' OR (LOCEMP LIKE 'HA_%' AND LOCEMP NOT LIKE 'HA8%') OR LOCEMP LIKE 'TW3%' OR LOCEMP LIKE 'TW4%' OR LOCEMP LIKE 'TW5%' OR LOCEMP LIKE 'TW6%' OR LOCEMP LIKE 'TW7%' OR LOCEMP LIKE 'TW8%' OR LOCEMP LIKE 'TW13%' OR LOCEMP LIKE 'TW14%' OR (LOCEMP LIKE 'UB_%' AND LOCEMP NOT LIKE 'UB9%')"
	),
	'Durham'	=> array(
		'sql'	=> "LOCEMP LIKE 'SR7%' OR LOCEMP LIKE 'SR8%' OR (LOCEMP LIKE 'DH_%' AND LOCEMP NOT LIKE 'DH4%' AND LOCEMP NOT LIKE 'DH5%') OR (LOCEMP LIKE 'DL_%' AND LOCEMP NOT LIKE 'DL6%' AND LOCEMP NOT LIKE 'DL7%' AND LOCEMP NOT LIKE 'DL8%' AND LOCEMP NOT LIKE 'DL9%' AND LOCEMP NOT LIKE 'DL10%' AND LOCEMP NOT LIKE 'DL11%') OR LOCEMP LIKE 'TS2%' OR LOCEMP LIKE 'TS16%' OR LOCEMP LIKE 'TS18%' OR LOCEMP LIKE 'TS19%'"
	),
	'North Yorkshire (NE England part)'	=> array(
		'sql'	=> "LOCEMP LIKE 'LS24%' OR (LOCEMP LIKE 'TS_%' AND LOCEMP NOT LIKE 'TS2%' AND LOCEMP NOT LIKE 'TS16%' AND LOCEMP NOT LIKE 'TS18%' AND LOCEMP NOT LIKE 'TS19%')"
	),
	'Northumberland'	=> array(
		'sql'	=> "LOCEMP LIKE 'NE18%' OR LOCEMP LIKE 'NE19%' OR LOCEMP LIKE 'NE20%' OR LOCEMP LIKE 'NE22%' OR LOCEMP LIKE 'NE23%' OR LOCEMP LIKE 'NE24%' OR LOCEMP LIKE 'NE43%' OR LOCEMP LIKE 'NE44%' OR LOCEMP LIKE 'NE45%' OR LOCEMP LIKE 'NE46%' OR LOCEMP LIKE 'NE47%' OR LOCEMP LIKE 'NE48%' OR LOCEMP LIKE 'NE49%' OR LOCEMP LIKE 'NE61%' OR LOCEMP LIKE 'NE62%' OR LOCEMP LIKE 'NE63%' OR LOCEMP LIKE 'NE64%' OR LOCEMP LIKE 'NE65%' OR LOCEMP LIKE 'NE66%' OR LOCEMP LIKE 'NE67%' OR LOCEMP LIKE 'NE68%' OR LOCEMP LIKE 'NE69%' OR LOCEMP LIKE 'NE70%' OR LOCEMP LIKE 'NE71%' OR LOCEMP LIKE 'TD15%'"
	),
	'Tyne and Wear'	=> array(
		'sql'	=> "(LOCEMP LIKE 'NE_%' AND LOCEMP NOT LIKE 'NE18%' AND LOCEMP NOT LIKE 'NE19%' AND LOCEMP NOT LIKE 'NE20%' AND LOCEMP NOT LIKE 'NE22%' AND LOCEMP NOT LIKE 'NE23%' AND LOCEMP NOT LIKE 'NE24%' AND LOCEMP NOT LIKE 'NE43%' AND LOCEMP NOT LIKE 'NE44%' AND LOCEMP NOT LIKE 'NE45%' AND LOCEMP NOT LIKE 'NE46%' AND LOCEMP NOT LIKE 'NE47%' AND LOCEMP NOT LIKE 'NE48%' AND LOCEMP NOT LIKE 'NE49%' AND LOCEMP NOT LIKE 'NE61%' AND LOCEMP NOT LIKE 'NE62%' AND LOCEMP NOT LIKE 'NE63%' AND LOCEMP NOT LIKE 'NE64%' AND LOCEMP NOT LIKE 'NE65%' AND LOCEMP NOT LIKE 'NE66%' AND LOCEMP NOT LIKE 'NE67%' AND LOCEMP NOT LIKE 'NE68%' AND LOCEMP NOT LIKE 'NE69%' AND LOCEMP NOT LIKE 'NE70%' AND LOCEMP NOT LIKE 'NE71%') OR (LOCEMP LIKE 'SR_%' AND LOCEMP NOT LIKE 'SR7%' AND LOCEMP NOT LIKE 'SR8%') OR LOCEMP LIKE 'DH4%' OR LOCEMP LIKE 'DH5%'"
	),
	'Cheshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'L24%' OR LOCEMP LIKE 'SK9%' OR LOCEMP LIKE 'SK10%' OR LOCEMP LIKE 'SK11%' OR LOCEMP LIKE 'SK12%' OR LOCEMP LIKE 'SY14%' OR (LOCEMP LIKE 'WA_%' AND LOCEMP NOT LIKE 'WA3 1%' AND LOCEMP NOT LIKE 'WA3 2%' AND LOCEMP NOT LIKE 'WA3 3%' AND LOCEMP NOT LIKE 'WA14%' AND LOCEMP NOT LIKE 'WA15%' AND LOCEMP NOT LIKE 'WA9%' AND LOCEMP NOT LIKE 'WA10%' AND LOCEMP NOT LIKE 'WA11%' AND LOCEMP NOT LIKE 'WA12%') OR LOCEMP LIKE 'CA_%' OR (LOCEMP LIKE 'CH_%' AND LOCEMP NOT LIKE 'CH25%' AND LOCEMP NOT LIKE 'CH26%' AND LOCEMP NOT LIKE 'CH27%' AND LOCEMP NOT LIKE 'CH28%' AND LOCEMP NOT LIKE 'CH29%' AND LOCEMP NOT LIKE 'CH30%' AND LOCEMP NOT LIKE 'CH31%' AND LOCEMP NOT LIKE 'CH32%' AND LOCEMP NOT LIKE 'CH41%' AND LOCEMP NOT LIKE 'CH42%' AND LOCEMP NOT LIKE 'CH43%' AND LOCEMP NOT LIKE 'CH44%' AND LOCEMP NOT LIKE 'CH45%' AND LOCEMP NOT LIKE 'CH46%' AND LOCEMP NOT LIKE 'CH47%' AND LOCEMP NOT LIKE 'CH48%' AND LOCEMP NOT LIKE 'CH49%' AND LOCEMP NOT LIKE 'CH60%' AND LOCEMP NOT LIKE 'CH61%' AND LOCEMP NOT LIKE 'CH62%' AND LOCEMP NOT LIKE 'CH63%' AND LOCEMP NOT LIKE 'CH5%' AND LOCEMP NOT LIKE 'CH6%' AND LOCEMP NOT LIKE 'CH7%' AND LOCEMP NOT LIKE 'CH8%') OR LOCEMP LIKE 'CW_%'"
	),
	'Cumbria'	=> array(
		'sql'	=> "LOCEMP LIKE 'LA_%' AND LOCEMP NOT LIKE 'BB%' AND LOCEMP NOT LIKE 'LA1%' AND LOCEMP NOT LIKE 'LA2%' AND LOCEMP NOT LIKE 'LA3%' AND LOCEMP NOT LIKE 'LA4%' AND LOCEMP NOT LIKE 'LA5%' AND LOCEMP NOT LIKE 'LA6%'"
	),
	'Greater Manchester'	=> array(
		'sql'	=> "LOCEMP LIKE 'BL_%' OR LOCEMP REGEXP '^M[0-9]+' OR (LOCEMP LIKE 'SK_%' AND LOCEMP NOT LIKE 'SK13%' AND LOCEMP NOT LIKE 'SK17%' AND LOCEMP NOT LIKE 'SK22%' AND LOCEMP NOT LIKE 'SK23%' AND LOCEMP NOT LIKE 'SK9%' AND LOCEMP NOT LIKE 'SK10%' AND LOCEMP NOT LIKE 'SK11%' AND LOCEMP NOT LIKE 'SK12%') OR LOCEMP LIKE 'WA3 1%' OR LOCEMP LIKE 'WA3 2%' OR LOCEMP LIKE 'WA3 3%' OR LOCEMP LIKE 'WA14%' OR LOCEMP LIKE 'WA15%' OR (LOCEMP LIKE 'WN_%' AND LOCEMP NOT LIKE 'WN8%') OR (LOCEMP LIKE 'OL_%' AND LOCEMP NOT LIKE 'OL14%')"
	),
	'Lancashire'	=> array(
		'sql'	=> "LOCEMP LIKE 'BB%' OR LOCEMP LIKE 'LA1%' OR LOCEMP LIKE 'LA2%' OR LOCEMP LIKE 'LA3%' OR LOCEMP LIKE 'LA4%' OR LOCEMP LIKE 'LA5%' OR LOCEMP LIKE 'LA6%' OR LOCEMP LIKE 'L39%' OR LOCEMP LIKE 'L40%' OR LOCEMP LIKE 'WN8%' OR LOCEMP LIKE 'FY_%' OR (LOCEMP LIKE 'PR_%' AND LOCEMP NOT LIKE 'PR8%' AND LOCEMP NOT LIKE 'PR9%')"
	),
	'Merseyside'	=> array(
		'sql'	=> "(LOCEMP LIKE 'L_%' AND LOCEMP NOT LIKE 'L24%' AND LOCEMP NOT LIKE 'L39%' AND LOCEMP NOT LIKE 'L40%' AND LOCEMP NOT LIKE 'LE%' AND LOCEMP NOT LIKE 'LS%' AND LOCEMP NOT LIKE 'LA%' AND LOCEMP NOT LIKE 'LL%' AND LOCEMP NOT LIKE 'LU%' AND LOCEMP NOT LIKE 'LN%') OR LOCEMP LIKE 'WA9%' OR LOCEMP LIKE 'WA10%' OR LOCEMP LIKE 'WA11%' OR LOCEMP LIKE 'WA12%' OR LOCEMP LIKE 'CH25%' OR LOCEMP LIKE 'CH26%' OR LOCEMP LIKE 'CH27%' OR LOCEMP LIKE 'CH28%' OR LOCEMP LIKE 'CH29%' OR LOCEMP LIKE 'CH30%' OR LOCEMP LIKE 'CH31%' OR LOCEMP LIKE 'CH32%' OR LOCEMP LIKE 'CH41%' OR LOCEMP LIKE 'CH42%' OR LOCEMP LIKE 'CH43%' OR LOCEMP LIKE 'CH44%' OR LOCEMP LIKE 'CH45%' OR LOCEMP LIKE 'CH46%' OR LOCEMP LIKE 'CH47%' OR LOCEMP LIKE 'CH48%' OR LOCEMP LIKE 'CH49%' OR LOCEMP LIKE 'CH60%' OR LOCEMP LIKE 'CH61%' OR LOCEMP LIKE 'CH62%' OR LOCEMP LIKE 'CH63%' OR LOCEMP LIKE 'PR8%' OR LOCEMP LIKE 'PR9%'"
	),
	'Berkshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'SL4%' OR LOCEMP LIKE 'SL5%' OR LOCEMP LIKE 'SL6%' OR LOCEMP LIKE 'SL95%' OR (LOCEMP LIKE 'RG_%' AND LOCEMP NOT LIKE 'RG21%' AND LOCEMP NOT LIKE 'RG22%' AND LOCEMP NOT LIKE 'RG23%' AND LOCEMP NOT LIKE 'RG24%' AND LOCEMP NOT LIKE 'RG25%' AND LOCEMP NOT LIKE 'RG26%' AND LOCEMP NOT LIKE 'RG27%' AND LOCEMP NOT LIKE 'RG28%' AND LOCEMP NOT LIKE 'RG29%' AND LOCEMP NOT LIKE 'RG8%' AND LOCEMP NOT LIKE 'RG9%')"
	),
	'Buckinghamshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'MK_%' OR (LOCEMP LIKE 'SL_%' AND LOCEMP NOT LIKE 'SL4%' AND LOCEMP NOT LIKE 'SL5%' AND LOCEMP NOT LIKE 'SL6%' AND LOCEMP NOT LIKE 'SL95%') OR (LOCEMP LIKE 'SL_%' AND LOCEMP LIKE 'SL4%' AND LOCEMP NOT LIKE 'SL5%' AND LOCEMP NOT LIKE 'SL6%' AND LOCEMP NOT LIKE 'SL95%') OR LOCEMP LIKE 'HP5%' OR LOCEMP LIKE 'HP6%' OR LOCEMP LIKE 'HP7%' OR LOCEMP LIKE 'HP8%' OR LOCEMP LIKE 'HP9%' OR LOCEMP LIKE 'HP10%' OR LOCEMP LIKE 'HP11%' OR LOCEMP LIKE 'HP12%' OR LOCEMP LIKE 'HP13%' OR LOCEMP LIKE 'HP14%' OR LOCEMP LIKE 'HP15%' OR LOCEMP LIKE 'HP16%' OR LOCEMP LIKE 'HP17%' OR LOCEMP LIKE 'HP18%' OR LOCEMP LIKE 'HP19%' OR LOCEMP LIKE 'HP20%' OR LOCEMP LIKE 'HP21%' OR LOCEMP LIKE 'HP22%' OR LOCEMP LIKE 'HP27%' OR LOCEMP LIKE 'UB9%'"
	),
	'East Sussex'	=> array(
		'sql'	=> "(LOCEMP LIKE 'BN50%' OR LOCEMP LIKE 'BN51%' OR LOCEMP LIKE 'BN52%') OR (LOCEMP LIKE 'BN_%' AND LOCEMP NOT LIKE 'BN6%' AND LOCEMP NOT LIKE 'BN11%' AND LOCEMP NOT LIKE 'BN12%' AND LOCEMP NOT LIKE 'BN13%' AND LOCEMP NOT LIKE 'BN14%' AND LOCEMP NOT LIKE 'BN15%' AND LOCEMP NOT LIKE 'BN16%' AND LOCEMP NOT LIKE 'BN17%' AND LOCEMP NOT LIKE 'BN18%' AND LOCEMP NOT LIKE 'BN42%' AND LOCEMP NOT LIKE 'BN43%' AND LOCEMP NOT LIKE 'BN44%' AND LOCEMP NOT LIKE 'BN45%' AND LOCEMP NOT LIKE 'BN99%') OR LOCEMP LIKE 'TN5%' OR LOCEMP LIKE 'TN6%' OR LOCEMP LIKE 'TN7%' OR LOCEMP LIKE 'TN19%' OR LOCEMP LIKE 'TN20%' OR LOCEMP LIKE 'TN21%' OR LOCEMP LIKE 'TN22%' OR LOCEMP LIKE 'TN31%' OR LOCEMP LIKE 'TN32%' OR LOCEMP LIKE 'TN33%' OR LOCEMP LIKE 'TN34%' OR LOCEMP LIKE 'TN35%' OR LOCEMP LIKE 'TN36%' OR LOCEMP LIKE 'TN37%' OR LOCEMP LIKE 'TN38%' OR LOCEMP LIKE 'TN39%' OR LOCEMP LIKE 'TN40%'"
	),
	'Hampshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'BH24%' OR LOCEMP LIKE 'BH25%' OR LOCEMP LIKE 'GU13%' OR LOCEMP LIKE 'GU11%' OR LOCEMP LIKE 'GU12%' OR LOCEMP LIKE 'GU14%' OR LOCEMP LIKE 'GU17%' OR LOCEMP LIKE 'GU30%' OR LOCEMP LIKE 'GU31%' OR LOCEMP LIKE 'GU32%' OR LOCEMP LIKE 'GU33%' OR LOCEMP LIKE 'GU34%' OR LOCEMP LIKE 'GU35%' OR LOCEMP LIKE 'GU46%' OR LOCEMP LIKE 'GU47%' OR LOCEMP LIKE 'GU51%' OR LOCEMP LIKE 'GU52%' OR LOCEMP LIKE 'SO_%' OR (LOCEMP LIKE 'PO_%' AND LOCEMP NOT LIKE 'PO30%' AND LOCEMP NOT LIKE 'PO31%' AND LOCEMP NOT LIKE 'PO32%' AND LOCEMP NOT LIKE 'PO33%' AND LOCEMP NOT LIKE 'PO34%' AND LOCEMP NOT LIKE 'PO35%' AND LOCEMP NOT LIKE 'PO36%' AND LOCEMP NOT LIKE 'PO37%' AND LOCEMP NOT LIKE 'PO38%' AND LOCEMP NOT LIKE 'PO39%' AND LOCEMP NOT LIKE 'PO40%' AND LOCEMP NOT LIKE 'PO41%' AND LOCEMP NOT LIKE 'PO18%' AND LOCEMP NOT LIKE 'PO19%' AND LOCEMP NOT LIKE 'PO20%' AND LOCEMP NOT LIKE 'PO21%' AND LOCEMP NOT LIKE 'PO22%') OR LOCEMP LIKE 'RG21%' OR LOCEMP LIKE 'RG22%' OR LOCEMP LIKE 'RG23%' OR LOCEMP LIKE 'RG24%' OR LOCEMP LIKE 'RG25%' OR LOCEMP LIKE 'RG26%' OR LOCEMP LIKE 'RG27%' OR LOCEMP LIKE 'RG28%' OR LOCEMP LIKE 'RG29%'"
	),
	'Isle of Wight'	=> array(
		'sql'	=> "LOCEMP LIKE 'PO30%' OR LOCEMP LIKE 'PO31%' OR LOCEMP LIKE 'PO32%' OR LOCEMP LIKE 'PO33%' OR LOCEMP LIKE 'PO34%' OR LOCEMP LIKE 'PO35%' OR LOCEMP LIKE 'PO36%' OR LOCEMP LIKE 'PO37%' OR LOCEMP LIKE 'PO38%' OR LOCEMP LIKE 'PO39%' OR LOCEMP LIKE 'PO40%' OR LOCEMP LIKE 'PO41%'"
	),
	'Kent'	=> array(
		'sql'	=> "LOCEMP LIKE 'BR8%' OR LOCEMP LIKE 'ME_%' OR LOCEMP LIKE 'CT_%' OR (LOCEMP LIKE 'DA_%' AND LOCEMP NOT LIKE 'DA6%' AND LOCEMP NOT LIKE 'DA7%' AND LOCEMP NOT LIKE 'DA8%' AND LOCEMP NOT LIKE 'DA14%' AND LOCEMP NOT LIKE 'DA15%' AND LOCEMP NOT LIKE 'DA16%' AND LOCEMP NOT LIKE 'DA17%' AND LOCEMP NOT LIKE 'DA18%' AND LOCEMP NOT LIKE 'DA5%') OR (LOCEMP LIKE 'TN_%' AND LOCEMP NOT LIKE 'TN5%' AND LOCEMP NOT LIKE 'TN6%' AND LOCEMP NOT LIKE 'TN7%' AND LOCEMP NOT LIKE 'TN19%' AND LOCEMP NOT LIKE 'TN20%' AND LOCEMP NOT LIKE 'TN21%' AND LOCEMP NOT LIKE 'TN22%' AND LOCEMP NOT LIKE 'TN31%' AND LOCEMP NOT LIKE 'TN32%' AND LOCEMP NOT LIKE 'TN33%' AND LOCEMP NOT LIKE 'TN34%' AND LOCEMP NOT LIKE 'TN35%' AND LOCEMP NOT LIKE 'TN36%' AND LOCEMP NOT LIKE 'TN37%' AND LOCEMP NOT LIKE 'TN38%' AND LOCEMP NOT LIKE 'TN39%' AND LOCEMP NOT LIKE 'TN40%' AND LOCEMP NOT LIKE 'TN14%' AND LOCEMP NOT LIKE 'TN16%')"
	),
	'Oxfordshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'SN7%' OR (LOCEMP LIKE 'OX_%' AND LOCEMP NOT LIKE 'OX17%') OR LOCEMP LIKE 'RG8%' OR LOCEMP LIKE 'RG9%'"
	),
	'Surrey'	=> array(
		'sql'	=> "(LOCEMP LIKE 'GU%' AND LOCEMP NOT LIKE 'GU13%' AND LOCEMP NOT LIKE 'GU11%' AND LOCEMP NOT LIKE 'GU12%' AND LOCEMP NOT LIKE 'GU14%' AND LOCEMP NOT LIKE 'GU17%' AND LOCEMP NOT LIKE 'GU30%' AND LOCEMP NOT LIKE 'GU31%' AND LOCEMP NOT LIKE 'GU32%' AND LOCEMP NOT LIKE 'GU33%' AND LOCEMP NOT LIKE 'GU34%' AND LOCEMP NOT LIKE 'GU35%' AND LOCEMP NOT LIKE 'GU46%' AND LOCEMP NOT LIKE 'GU47%' AND LOCEMP NOT LIKE 'GU51%' AND LOCEMP NOT LIKE 'GU52%' AND LOCEMP NOT LIKE 'GU28%' AND LOCEMP NOT LIKE 'GU29%') OR LOCEMP LIKE 'SM7%' OR LOCEMP LIKE 'SP6%' OR LOCEMP LIKE 'SP10%' OR LOCEMP LIKE 'SP11%' OR LOCEMP LIKE 'CR6%' OR LOCEMP LIKE 'KT7%' OR LOCEMP LIKE 'KT8%' OR LOCEMP LIKE 'KT10%' OR LOCEMP LIKE 'KT11%' OR LOCEMP LIKE 'KT12%' OR LOCEMP LIKE 'KT13%' OR LOCEMP LIKE 'KT14%' OR LOCEMP LIKE 'KT15%' OR LOCEMP LIKE 'KT16%' OR LOCEMP LIKE 'KT17%' OR LOCEMP LIKE 'KT18%' OR LOCEMP LIKE 'KT19%' OR LOCEMP LIKE 'KT20%' OR LOCEMP LIKE 'KT21%' OR LOCEMP LIKE 'KT22%' OR LOCEMP LIKE 'KT23%' OR LOCEMP LIKE 'KT24%' OR (LOCEMP LIKE 'RH_%' AND LOCEMP NOT LIKE 'RH10%' AND LOCEMP NOT LIKE 'RH11%' AND LOCEMP NOT LIKE 'RH12%' AND LOCEMP NOT LIKE 'RH13%' AND LOCEMP NOT LIKE 'RH14%' AND LOCEMP NOT LIKE 'RH15%' AND LOCEMP NOT LIKE 'RH16%' AND LOCEMP NOT LIKE 'RH17%' AND LOCEMP NOT LIKE 'RH18%' AND LOCEMP NOT LIKE 'RH19%' AND LOCEMP NOT LIKE 'RH20%') OR LOCEMP LIKE 'TW15%' OR LOCEMP LIKE 'TW16%' OR LOCEMP LIKE 'TW17%' OR LOCEMP LIKE 'TW18%' OR LOCEMP LIKE 'TW19%' OR LOCEMP LIKE 'TW20%'"
	),
	'West Sussex'	=> array(
		'sql'	=> "(LOCEMP LIKE 'BN5%' AND LOCEMP NOT LIKE 'BN50%' AND LOCEMP NOT LIKE 'BN51%' AND LOCEMP NOT LIKE 'BN52%') OR LOCEMP LIKE 'BN6%' OR LOCEMP LIKE 'BN11%' OR LOCEMP LIKE 'BN12%' OR LOCEMP LIKE 'BN13%' OR LOCEMP LIKE 'BN14%' OR LOCEMP LIKE 'BN15%' OR LOCEMP LIKE 'BN16%' OR LOCEMP LIKE 'BN17%' OR LOCEMP LIKE 'BN18%' OR LOCEMP LIKE 'BN42%' OR LOCEMP LIKE 'BN43%' OR LOCEMP LIKE 'BN44%' OR LOCEMP LIKE 'BN45%' OR LOCEMP LIKE 'BN99%' OR LOCEMP LIKE 'GU28%' OR LOCEMP LIKE 'GU29%' OR LOCEMP LIKE 'PO18%' OR LOCEMP LIKE 'PO19%' OR LOCEMP LIKE 'PO20%' OR LOCEMP LIKE 'PO21%' OR LOCEMP LIKE 'PO22%' OR LOCEMP LIKE 'RH10%' OR LOCEMP LIKE 'RH11%' OR LOCEMP LIKE 'RH12%' OR LOCEMP LIKE 'RH13%' OR LOCEMP LIKE 'RH14%' OR LOCEMP LIKE 'RH15%' OR LOCEMP LIKE 'RH16%' OR LOCEMP LIKE 'RH17%' OR LOCEMP LIKE 'RH18%' OR LOCEMP LIKE 'RH19%' OR LOCEMP LIKE 'RH20%'"
	),
	'Bristol'	=> array(
		'sql'	=>"LOCEMP LIKE 'BS_%' AND LOCEMP NOT LIKE 'BS20%' AND LOCEMP NOT LIKE 'BS21%' AND LOCEMP NOT LIKE 'BS22%' AND LOCEMP NOT LIKE 'BS23%' AND LOCEMP NOT LIKE 'BS24%' AND LOCEMP NOT LIKE 'BS25%' AND LOCEMP NOT LIKE 'BS26%' AND LOCEMP NOT LIKE 'BS27%' AND LOCEMP NOT LIKE 'BS28%' AND LOCEMP NOT LIKE 'BS29%' AND LOCEMP NOT LIKE 'BS31%' AND LOCEMP NOT LIKE 'BS39%' AND LOCEMP NOT LIKE 'BS40%' AND LOCEMP NOT LIKE 'BS41%' AND LOCEMP NOT LIKE 'BS48%' AND LOCEMP NOT LIKE 'BS49%' AND LOCEMP NOT LIKE 'BS15%' AND LOCEMP NOT LIKE 'BS16%' AND LOCEMP NOT LIKE 'BS30%' AND LOCEMP NOT LIKE 'BS31%' AND LOCEMP NOT LIKE 'BS32%' AND LOCEMP NOT LIKE 'BS34%' AND LOCEMP NOT LIKE 'BS35%' AND LOCEMP NOT LIKE 'BS36%' AND LOCEMP NOT LIKE 'BS37%'"
	),
	'Cornwall'	=> array(
		'sql'	=> "LOCEMP LIKE 'EX23%' OR LOCEMP LIKE 'PL10%' OR LOCEMP LIKE 'PL11%' OR LOCEMP LIKE 'PL12%' OR LOCEMP LIKE 'PL13%' OR LOCEMP LIKE 'PL14%' OR LOCEMP LIKE 'PL15%' OR LOCEMP LIKE 'PL17%' OR LOCEMP LIKE 'PL18%' OR LOCEMP LIKE 'PL22%' OR LOCEMP LIKE 'PL23%' OR LOCEMP LIKE 'PL24%' OR LOCEMP LIKE 'PL25%' OR LOCEMP LIKE 'PL26%' OR LOCEMP LIKE 'PL27%' OR LOCEMP LIKE 'PL28%' OR LOCEMP LIKE 'PL29%' OR LOCEMP LIKE 'PL30%' OR LOCEMP LIKE 'PL31%' OR LOCEMP LIKE 'PL32%' OR LOCEMP LIKE 'PL33%' OR LOCEMP LIKE 'PL34%' OR LOCEMP LIKE 'PL35%' OR LOCEMP LIKE 'TR_%'"
	),
	'Devon'	=> array(
		'sql'	=> "LOCEMP LIKE 'EX_%' AND LOCEMP NOT LIKE 'EX23%' OR (LOCEMP LIKE 'PL_%' AND LOCEMP NOT LIKE 'PL10%' AND LOCEMP NOT LIKE 'PL11%' AND LOCEMP NOT LIKE 'PL12%' AND LOCEMP NOT LIKE 'PL13%' AND LOCEMP NOT LIKE 'PL14%' AND LOCEMP NOT LIKE 'PL15%' AND LOCEMP NOT LIKE 'PL17%' AND LOCEMP NOT LIKE 'PL18%' AND LOCEMP NOT LIKE 'PL22%' AND LOCEMP NOT LIKE 'PL23%' AND LOCEMP NOT LIKE 'PL24%' AND LOCEMP NOT LIKE 'PL25%' AND LOCEMP NOT LIKE 'PL26%' AND LOCEMP NOT LIKE 'PL27%' AND LOCEMP NOT LIKE 'PL28%' AND LOCEMP NOT LIKE 'PL29%' AND LOCEMP NOT LIKE 'PL30%' AND LOCEMP NOT LIKE 'PL31%' AND LOCEMP NOT LIKE 'PL32%' AND LOCEMP NOT LIKE 'PL33%' AND LOCEMP NOT LIKE 'PL34%' AND LOCEMP NOT LIKE 'PL35%') OR LOCEMP LIKE 'TQ_%'"
	),
	'Dorset'	=> array(
		'sql'	=>"(LOCEMP LIKE 'BH_%' AND LOCEMP NOT LIKE 'BH24%' AND LOCEMP NOT LIKE 'BH25%') OR LOCEMP LIKE 'SP7%' OR LOCEMP LIKE 'SP8%' OR LOCEMP LIKE 'DT_%'"
	),
	'Gloucestershire'	=> array(
		'sql'	=> "LOCEMP LIKE 'BS15%' OR LOCEMP LIKE 'BS16%' OR LOCEMP LIKE 'BS30%' OR LOCEMP LIKE 'BS31%' OR LOCEMP LIKE 'BS32%' OR LOCEMP LIKE 'BS34%' OR LOCEMP LIKE 'BS35%' OR LOCEMP LIKE 'BS36%' OR LOCEMP LIKE 'BS37%' OR LOCEMP LIKE 'GL%'"
	),
	'Somerset'	=> array(
		'sql'	=> "(LOCEMP LIKE 'BA_%' AND LOCEMP NOT LIKE 'BA12' AND LOCEMP NOT LIKE 'BA13' AND LOCEMP NOT LIKE 'BA14' AND LOCEMP NOT LIKE 'BA15') OR (LOCEMP LIKE 'BS20%' OR LOCEMP LIKE 'BS21%' OR LOCEMP LIKE 'BS22%' OR LOCEMP LIKE 'BS23%' OR LOCEMP LIKE 'BS24%' OR LOCEMP LIKE 'BS25%' OR LOCEMP LIKE 'BS26%' OR LOCEMP LIKE 'BS27%' OR LOCEMP LIKE 'BS28%' OR LOCEMP LIKE 'BS29%' OR LOCEMP LIKE 'BS31%' OR LOCEMP LIKE 'BS39%' OR LOCEMP LIKE 'BS40%' OR LOCEMP LIKE 'BS41%' OR LOCEMP LIKE 'BS48%' OR LOCEMP LIKE 'BS49%') OR LOCEMP LIKE 'TA_%'"
	),
	'Wiltshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'BA12%' OR LOCEMP LIKE 'BA13%' OR LOCEMP LIKE 'BA14%' OR LOCEMP LIKE 'BA15%' OR (LOCEMP LIKE 'SN_%' AND LOCEMP NOT LIKE 'SN7%') OR (LOCEMP LIKE 'SP_%' AND LOCEMP NOT LIKE 'SP7%' AND LOCEMP NOT LIKE 'SP8%' AND LOCEMP NOT LIKE 'SP6%' AND LOCEMP NOT LIKE 'SP10%' AND LOCEMP NOT LIKE 'SP11%')"
	),
	'Herefordshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'HR_%'"
	),
	'Shropshire'	=> array(
		'sql'	=> "(LOCEMP LIKE 'SY_%' AND LOCEMP NOT LIKE 'SY14%' AND LOCEMP NOT LIKE 'SY15%' AND LOCEMP NOT LIKE 'SY16%' AND LOCEMP NOT LIKE 'SY17%' AND LOCEMP NOT LIKE 'SY18%' AND LOCEMP NOT LIKE 'SY19%' AND LOCEMP NOT LIKE 'SY20%' AND LOCEMP NOT LIKE 'SY21%' AND LOCEMP NOT LIKE 'SY22%' AND LOCEMP NOT LIKE 'SY23%' AND LOCEMP NOT LIKE 'SY24%' AND LOCEMP NOT LIKE 'SY25%') OR LOCEMP LIKE 'WV15%' OR LOCEMP LIKE 'WV16%' OR LOCEMP LIKE 'DY14%' OR LOCEMP LIKE 'TF_%'"
	),
	'Staffordshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'B77%' OR LOCEMP LIKE 'B78%' OR LOCEMP LIKE 'B79%' OR LOCEMP LIKE 'ST_%' OR LOCEMP LIKE 'WR_%' OR LOCEMP LIKE 'WS6%' OR LOCEMP LIKE 'WS7%' OR LOCEMP LIKE 'WS11%' OR LOCEMP LIKE 'WS12%' OR LOCEMP LIKE 'WS13%' OR LOCEMP LIKE 'WS14%' OR LOCEMP LIKE 'WS15%' OR LOCEMP LIKE 'WV5%' OR LOCEMP LIKE 'DE14%' OR LOCEMP LIKE 'DE15%' OR LOCEMP LIKE 'DY14%'"
	),
	'Warwickshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'B46%' OR LOCEMP LIKE 'B49%' OR LOCEMP LIKE 'B50%' OR LOCEMP LIKE 'B80%' OR LOCEMP LIKE 'B95%' OR LOCEMP LIKE 'CV7%' OR LOCEMP LIKE 'CV8%' OR LOCEMP LIKE 'CV9%' OR LOCEMP LIKE 'CV10%' OR LOCEMP LIKE 'CV11%' OR LOCEMP LIKE 'CV12%' OR LOCEMP LIKE 'CV21%' OR LOCEMP LIKE 'CV22%' OR LOCEMP LIKE 'CV23%' OR LOCEMP LIKE 'CV31%' OR LOCEMP LIKE 'CV32%' OR LOCEMP LIKE 'CV33%' OR LOCEMP LIKE 'CV34%' OR LOCEMP LIKE 'CV35%' OR LOCEMP LIKE 'CV36%' OR LOCEMP LIKE 'CV37%' OR LOCEMP LIKE 'CV47%'"
	),
	'West Midlands (county)'	=> array(
		'sql'	=> "(LOCEMP REGEXP '^B[0-9]+' AND LOCEMP NOT LIKE 'B46%' AND LOCEMP NOT LIKE 'B49%' AND LOCEMP NOT LIKE 'B50%' AND LOCEMP NOT LIKE 'B80%' AND LOCEMP NOT LIKE 'B95%' AND LOCEMP NOT LIKE 'B47%' AND LOCEMP NOT LIKE 'B48%' AND LOCEMP NOT LIKE 'B60%' AND LOCEMP NOT LIKE 'B61%' AND LOCEMP NOT LIKE 'B96%' AND LOCEMP NOT LIKE 'B97%' AND LOCEMP NOT LIKE 'B98%' AND LOCEMP NOT LIKE 'B77%' AND LOCEMP NOT LIKE 'B78%' AND LOCEMP NOT LIKE 'B79%') OR (LOCEMP LIKE 'WS_%' AND LOCEMP NOT LIKE 'WS6%' AND LOCEMP NOT LIKE 'WS7%' AND LOCEMP NOT LIKE 'WS11%' AND LOCEMP NOT LIKE 'WS12%' AND LOCEMP NOT LIKE 'WS13%' AND LOCEMP NOT LIKE 'WS14%' AND LOCEMP NOT LIKE 'WS15%') OR (LOCEMP LIKE 'WV_%' AND LOCEMP NOT LIKE 'WV5%' AND LOCEMP NOT LIKE 'WV15%' AND LOCEMP NOT LIKE 'WV16%') OR (LOCEMP LIKE 'CV_%' AND LOCEMP NOT LIKE 'CV7%' AND LOCEMP NOT LIKE 'CV8%' AND LOCEMP NOT LIKE 'CV9%' AND LOCEMP NOT LIKE 'CV10%' AND LOCEMP NOT LIKE 'CV11%' AND LOCEMP NOT LIKE 'CV12%' AND LOCEMP NOT LIKE 'CV21%' AND LOCEMP NOT LIKE 'CV22%' AND LOCEMP NOT LIKE 'CV23%' AND LOCEMP NOT LIKE 'CV31%' AND LOCEMP NOT LIKE 'CV32%' AND LOCEMP NOT LIKE 'CV33%' AND LOCEMP NOT LIKE 'CV34%' AND LOCEMP NOT LIKE 'CV35%' AND LOCEMP NOT LIKE 'CV36%' AND LOCEMP NOT LIKE 'CV37%' AND LOCEMP NOT LIKE 'CV47%' AND LOCEMP NOT LIKE 'CV13%') OR (LOCEMP LIKE 'DY_%' AND LOCEMP NOT LIKE 'DY10%' AND LOCEMP NOT LIKE 'DY11%' AND LOCEMP NOT LIKE 'DY12%' AND LOCEMP NOT LIKE 'DY13%' AND LOCEMP NOT LIKE 'DY14%' AND LOCEMP NOT LIKE 'DY14%')"
	),
	'Worcestershire'	=> array(
		'sql'	=> "LOCEMP LIKE 'B47%' OR LOCEMP LIKE 'B48%' OR LOCEMP LIKE 'B60%' OR LOCEMP LIKE 'B61%' OR LOCEMP LIKE 'B96%' OR LOCEMP LIKE 'B97%' OR LOCEMP LIKE 'B98%' OR LOCEMP LIKE 'DY10%' OR LOCEMP LIKE 'DY11%' OR LOCEMP LIKE 'DY12%' OR LOCEMP LIKE 'DY13%'"
	),
	'East Riding of Yorkshire'	=> array(
		'sql'	=> "LOCEMP LIKE 'DN14%' OR LOCEMP LIKE 'HU_%' OR LOCEMP LIKE 'YO15%' OR LOCEMP LIKE 'YO16%' OR LOCEMP LIKE 'YO25%' OR LOCEMP LIKE 'YO41%' OR LOCEMP LIKE 'YO42%' OR LOCEMP LIKE 'YO43%'"
	),
	'Lincolnshire (Yorks. part)'	=> array(
		'sql'	=> "LOCEMP LIKE 'DN15%' OR LOCEMP LIKE 'DN16%' OR LOCEMP LIKE 'DN17%' OR LOCEMP LIKE 'DN18%' OR LOCEMP LIKE 'DN19%' OR LOCEMP LIKE 'DN20%' OR LOCEMP LIKE 'DN31%' OR LOCEMP LIKE 'DN32%' OR LOCEMP LIKE 'DN33%' OR LOCEMP LIKE 'DN34%' OR LOCEMP LIKE 'DN35%' OR LOCEMP LIKE 'DN37%' OR LOCEMP LIKE 'DN38%' OR LOCEMP LIKE 'DN39%' OR LOCEMP LIKE 'DN40%' OR LOCEMP LIKE 'DN41%'"
	),
	'North Yorkshire (Yorks. part)'	=> array(
		'sql'	=> "LOCEMP LIKE 'BD23%' OR LOCEMP LIKE 'BD24%' OR LOCEMP LIKE 'DL6%' OR LOCEMP LIKE 'DL7%' OR LOCEMP LIKE 'DL8%' OR LOCEMP LIKE 'DL9%' OR LOCEMP LIKE 'DL10%' OR LOCEMP LIKE 'DL11%' OR (LOCEMP LIKE 'YO_%' AND LOCEMP NOT LIKE 'YO15%' AND LOCEMP NOT LIKE 'YO16%' AND LOCEMP NOT LIKE 'YO25%' AND LOCEMP NOT LIKE 'YO41%' AND LOCEMP NOT LIKE 'YO42%' AND LOCEMP NOT LIKE 'YO43%') OR LOCEMP LIKE 'HG%'"
	),
	'South Yorkshire'	=> array(
		'sql'	=>"(LOCEMP REGEXP '^S[0-9]+' AND LOCEMP NOT LIKE 'S18%' AND LOCEMP NOT LIKE 'S21%' AND LOCEMP NOT LIKE 'S32%' AND LOCEMP NOT LIKE 'S33%' AND LOCEMP NOT LIKE 'S40%' AND LOCEMP NOT LIKE 'S41%' AND LOCEMP NOT LIKE 'S42%' AND LOCEMP NOT LIKE 'S43%' AND LOCEMP NOT LIKE 'S44%' AND LOCEMP NOT LIKE 'S45%' AND LOCEMP NOT LIKE 'S49%' AND LOCEMP NOT LIKE 'S80%' AND LOCEMP NOT LIKE 'S81%') OR (LOCEMP LIKE 'DN_%' AND LOCEMP NOT LIKE 'DN15%' AND LOCEMP NOT LIKE 'DN16%' AND LOCEMP NOT LIKE 'DN17%' AND LOCEMP NOT LIKE 'DN18%' AND LOCEMP NOT LIKE 'DN19%' AND LOCEMP NOT LIKE 'DN20%' AND LOCEMP NOT LIKE 'DN31%' AND LOCEMP NOT LIKE 'DN32%' AND LOCEMP NOT LIKE 'DN33%' AND LOCEMP NOT LIKE 'DN34%' AND LOCEMP NOT LIKE 'DN35%' AND LOCEMP NOT LIKE 'DN37%' AND LOCEMP NOT LIKE 'DN38%' AND LOCEMP NOT LIKE 'DN39%' AND LOCEMP NOT LIKE 'DN40%' AND LOCEMP NOT LIKE 'DN41%' AND LOCEMP NOT LIKE 'DN10%' AND LOCEMP NOT LIKE 'DN11%' AND LOCEMP NOT LIKE 'DN22%' AND LOCEMP NOT LIKE 'DN14%' AND LOCEMP NOT LIKE 'DN21%' AND LOCEMP NOT LIKE 'DN36%')"
		),
	'West Yorkshire'	=> array(
		'sql'	=> "(LOCEMP LIKE 'BD_%' AND LOCEMP NOT LIKE 'BD23%' AND LOCEMP NOT LIKE 'BD24%') OR (LOCEMP LIKE 'LS_%' AND LOCEMP NOT LIKE 'LS24%') OR LOCEMP LIKE 'WF_%' OR LOCEMP LIKE 'HD_%' OR LOCEMP LIKE 'HX_%' OR LOCEMP LIKE 'OL14%'"
	),
);

$postregions = array(
	'Northern Ireland'			=> array(
		'Antrim', 'Ards', 'Armagh', 'Ballymena', 'Ballymoney', 'Banbridge', 'Belfast', 'Carrickfergus', 'Castlereagh', 'Coleraine', 'Cookstown', 'Craigavon', 'Derry', 'Down', 'Dungannon and South Tyrone', 'Fermanagh', 'Larne', 'Limavady', 'Lisburn', 'Magherafelt', 'Moyle', 'Newry and Mourne', 'Newtownabbey', 'North Down', 'Omagh', 'Strabane'
	),
	'Scotland'					=> array(
		'Aberdeen City', 'Aberdeenshire', 'Angus', 'Argyll and Bute', 'Clackmannanshire', 'Dumfries and Galloway', 'Dundee City', 'East Ayrshire', 'East Dunbartonshire', 'East Lothian', 'East Renfrewshire', 'City of Edinburgh', 'Falkirk', 'Fife', 'Glasgow City', 'Highland', 'Inverclyde', 'Midlothian', 'Moray', 'Na h-Eilanan Siar', 'North Ayrshire', 'North Lanarkshire', 'Orkney Islands', 'Perth and Kinross', 'Renfrewshire', 'Scottish Borders', 'Shetland Islands', 'South Ayrshire', 'South Lanarkshire', 'Stirling', 'West Dunbartonshire', 'West Lothian'
	),
	'Wales'						=> array(
		'Blaenau Gwent', 'Bridgend', 'Caerphilly', 'Cardiff', 'Carmarthenshire', 'Ceredigion', 'Conwy', 'Denbighshire', 'Flintshire', 'Gwynedd', 'Isle of Anglesey', 'Merthyr Tydfil', 'Monmouthshire', 'Neath Port Talbot', 'Newport', 'Pembrokeshire', 'Powys', 'Rhondda', 'Swansea', 'Torfaen', 'Vale of Glamorgan', 'Wrexham'
	),
	'East Midlands'				=> array(
		'Derbyshire', 'Leicestershire', 'Lincolnshire (E. Midlands part)', 'Northamptonshire', 'Nottinghamshire', 'Rutland'
	),
	'East of England'			=> array(
		'Bedfordshire', 'Cambridgeshire', 'Essex', 'Hertfordshire', 'Norfolk', 'Suffolk'
	),
	'Greater London'			=> array(
		'North London', 'North East London', 'South East London', 'South West London', 'West London'
	),
	'North East England'		=> array(
		'Durham', 'North Yorkshire (NE England part)', 'Northumberland', 'Tyne and Wear'
	),
	'North West England'			=> array(
		'Cheshire', 'Cumbria', 'Greater Manchester', 'Lancashire', 'Merseyside'
	),
	'South East England'		=> array(
		'Berkshire', 'Buckinghamshire', 'East Sussex', 'Hampshire', 'Isle of Wight', 'Kent', 'Oxfordshire', 'Surrey', 'West Sussex'
	),
	'South West England'		=> array(
		'Bristol', 'Cornwall', 'Devon', 'Dorset', 'Gloucestershire', 'Somerset', 'Wiltshire'
	),
	'West Midlands'				=> array(
		'Herefordshire', 'Shropshire', 'Staffordshire', 'Warwickshire', 'West Midlands (county)', 'Worcestershire'
	),
	'Yorkshire and the Humber'	=> array(
		'East Riding of Yorkshire', 'Lincolnshire (Yorks. part)', 'North Yorkshire (Yorks. part)', 'South Yorkshire', 'West Yorkshire'
	)
);

$gmapslu = array(
	'Northern Ireland'			=> 'newry|derry',
	'Scotland'					=> 'elgin|glasgow',
	'Wales'						=> 'swansea,gb',
	'East Midlands'				=> 'derby,gb',
	'East of England'			=> 'cambridge,gb',
	'Greater London'			=> 'kensington,gb',
	'North East England'		=> 'durham,gb',
	'North West England'		=> 'manchester,gb',
	'South East England'		=> 'crawley,gb',
	'South West England'		=> 'exeter,gb',
	'West Midlands'				=> 'walsall,gb',
	'Yorkshire and the Humber'	=> 'york,gb'
);

$gmapsmk = array(
	'78'	=> 'yellow',
	'89'	=> 'red',
	'910'	=> 'blue',
	'1011'	=> 'green',
	'1112'	=> 'purple'
);

?>